### ISSUE TITLE
Option to delete unlinked media

### ISSUE THREAD

**Issue by ShreyasKallingal** [Vinzent03/find-unlinked-files#6]
This plugin is great so far! I think it would be quite useful to implement a feature that sends unlinked files to the system trash folder. In particular, you could filter by media extensions (.png, .jpg, etc.) and save space on files that are not being used.

**Comment by Vinzent03** [comment]
Great idea!
My implementation would be a command that deletes all files in the output list with certain extensions, that can be set in the settings. Is this what you want?

**Comment by ShreyasKallingal** [comment]
That sounds great. Maybe there could be an option to move the files to the trash, since deletion is a bit extreme.

**Comment by Vinzent03** [comment]
I will take a look, but I think it uses the Obsidian setting, where you can set whether to delete, move to system trash or move to obsidian trash.

**Comment by ShreyasKallingal** [comment]
Oh right, that's ideal then.

**Comment by trungng2006** [comment]
Could you help me elaborate on how to implement this function?
I updated the plugin to 0.3.0. however, i do not know how to implement this function.

**Comment by Vinzent03** [comment]
@trungng2006 There should be a new command called delete unlinked files with certain extension. You can set the extensions in the settings.

**Comment by ShreyasKallingal** [comment]
By the way, thank you for implementing it so quickly! It's just what I wanted :)

**Comment by Vinzent03** [comment]
Great to hear. It could have been even more quickly, but I needed to figure out how to make a confirmation dialog. Although the buttons are still not centered. :)

**Comment by trungng2006** [comment]
> 
> 
> @trungng2006 There should be a new command called delete unlinked files with certain extension. You can set the extensions in the settings.

I stil cannot find this command. I checked in both the plugin's page in setting, and in ctrl+P.
Sorry for the trouble, but could you help me further?

**Comment by Vinzent03** [comment]
Maybe classic Obsidian restart? Or press `Ctrl + Shift + I` to see if there is any error.

**Comment by trungng2006** [comment]
Thank you so much!! it showed up in ctrl+P after restart :D

**Comment by knifelees3** [comment]
I found that I can't delete the files listed in the "unlinked files output" file., this files to be deleted have been successfully listed in the output files, but the command has been run without any message, is there anything wrong with my use?

**Comment by Vinzent03** [comment]
Have you entered the correct file extension in the plugin's settings? For normal notes it's `md`.

**Comment by knifelees3** [comment]
> @knifelees3 Have you entered the correct file extension in the plugin's settings? For normal notes it's `md`.

Do you mean the set : "Filetypes to delete per command. See Readme"? I type "png,jpg" to hope to delete the unused pictures,but it just doesn't work·····

**Comment by knifelees3** [comment]
> @knifelees3 Have you entered the correct file extension in the plugin's settings? For normal notes it's `md`.

Ok, I understand! I know how to correctly set the extension, the enable and disable make me confused . 

And I have another question, Will the picture file which is linked with general markdown format `![]()` be taken into account? Or some other files which are linked with HTML format (for example I link the video use HTML format). I worry that if I use the general markdown format to include files, this extension can't detect this and consider these files as unlinked files and will delete these files

**Comment by knifelees3** [comment]
@Vinzent03 Ok, I understand the correct use now. I was confused by the enable and disable choices in the settings at the first time
